version: '3.8'

services:
  kanban-demo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - FRONTEND_ORIGIN=http://localhost:8080
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    volumes:
      - ./logs:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
